spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: test
    password: test
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    generate-ddl: false
  h2:
    console:
      enabled: false
server:
  servlet:
    context-path: /api
logging:
  level:
    '[org.springframework.web]': info
    