CREATE TABLE PRICES (
    BRAND_ID BIGINT NOT NULL,
    START_DATE DATETIME NOT NULL,
    END_DATE DATETIME NOT NULL,
    PRICE_LIST BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    PRIORITY INTEGER NOT NULL, 
    PRICE DECIMAL(5,2) NOT NULL,
    CURR VARCHAR(50) NOT NULL
);